export const ADMISSION_APPLICATION_FIELDS = [
    { field: "applicationId", type: "String", required: "Auto", description: "Unique application ID (ADM-YYYY-XXXXXX)" },
    { field: "school", type: "ObjectId", required: "Yes", description: "School reference" },
    { field: "academicYear", type: "String", required: "Yes", description: "Academic year (e.g., '2025-2026')" },
    { field: "firstName", type: "String", required: "Yes", description: "Student's first name" },
    { field: "lastName", type: "String", required: "Yes", description: "Student's last name" },
    { field: "middleName", type: "String", required: "No", description: "Student's middle name" },
    { field: "aadharNumber", type: "String", required: "Yes", description: "12-digit Aadhar number" },
    { field: "dateOfBirth", type: "Date", required: "Yes", description: "Date of birth" },
    { field: "gender", type: "Enum", required: "Yes", description: "male, female, other" },
    { field: "category", type: "Enum", required: "Yes", description: "general, obc, sc, st, ews, other" },
    { field: "subCategory", type: "String", required: "No", description: "Sub-category details" },
    { field: "religion", type: "Enum", required: "Yes", description: "hinduism, islam, christianity, etc." },
    { field: "bloodGroup", type: "Enum", required: "No", description: "A+, A-, B+, B-, AB+, AB-, O+, O-" },
    { field: "nationality", type: "String", required: "No", description: "Default: Indian" },
    { field: "hasDisability", type: "Boolean", required: "No", description: "Default: false" },
    { field: "disabilityType", type: "String", required: "No", description: "Type of disability" },
    { field: "disabilityPercentage", type: "Number", required: "No", description: "Percentage of disability" },
    { field: "achievements", type: "Array", required: "No", description: "List of achievements" },
    { field: "classOfAdmission", type: "ObjectId", required: "Yes", description: "Class reference" },
    { field: "section", type: "String", required: "No", description: "Assigned after approval" },
    { field: "rollNumber", type: "String", required: "No", description: "Assigned after approval" },
    { field: "dateOfJoining", type: "Date", required: "No", description: "Joining date" },
    { field: "busNeeded", type: "Boolean", required: "No", description: "Default: false" },
    { field: "busRoute", type: "ObjectId", required: "No", description: "Transport route reference" },
    { field: "busStop", type: "String", required: "No", description: "Bus stop name" },
    { field: "hostelNeeded", type: "Boolean", required: "No", description: "Default: false" },
    { field: "hostelRoom", type: "ObjectId", required: "No", description: "Room reference" },
    { field: "currentAddress", type: "Object", required: "Yes", description: "Current address details" },
    { field: "permanentAddress", type: "Object", required: "Yes", description: "Permanent address details" },
    { field: "sameAsCurrentAddress", type: "Boolean", required: "No", description: "Same address flag" },
    { field: "familyInfo", type: "Object", required: "Yes", description: "Family details object" },
    { field: "documents", type: "Object", required: "No", description: "Document URLs" },
    { field: "status", type: "Enum", required: "Yes", description: "Workflow status" },
    { field: "parentAccounts", type: "Array", required: "No", description: "Parent user references" },
    { field: "studentAccount", type: "ObjectId", required: "No", description: "Student user reference" },
];

export const FEE_COMPONENT_FIELDS = [
    { field: "name", type: "String", required: "Yes", description: "Component name" },
    { field: "type", type: "Enum", required: "Yes", description: "tuition, books, uniform, hostel, transportation, custom, etc." },
    { field: "amount", type: "Number", required: "Yes", description: "Fee amount" },
    { field: "frequency", type: "Enum", required: "No", description: "one_time, monthly, quarterly, half_yearly, yearly" },
    { field: "isOptional", type: "Boolean", required: "No", description: "Default: false" },
    { field: "isActive", type: "Boolean", required: "No", description: "Default: true" },
    { field: "isCustom", type: "Boolean", required: "No", description: "Default: false" },
    { field: "dueDate", type: "Date", required: "No", description: "Payment due date" },
];

export const APPLICATION_STATUS = {
    DRAFT: "draft",
    SUBMITTED: "submitted",
    PENDING_ADMISSION_REVIEW: "pending_admission_review",
    REJECTED_BY_ADMISSION: "rejected_by_admission",
    PENDING_FEE_STRUCTURE: "pending_fee_structure",
    PENDING_PRINCIPAL_APPROVAL: "pending_principal_approval",
    REJECTED_BY_PRINCIPAL: "rejected_by_principal",
    APPROVED: "approved",
    ENROLLED: "enrolled",
    CANCELLED: "cancelled",
    WITHDRAWN: "withdrawn",
};

export const PURCHASE_REQUEST_STATUS = {
    DRAFT: "draft",
    PENDING: "pending",
    APPROVED: "approved",
    REJECTED: "rejected",
    PURCHASED: "purchased",
    DELIVERED: "delivered",
    CANCELLED: "cancelled",
};
